export const ADD_ACHIEVEMENTS_INFO_FULFILLED =
  "ADD_ACHIEVEMENTS_INFO_FULFILLED";
export const ADD_ACHIEVEMENTS_INFO_PENDING = "ADD_ACHIEVEMENTS_INFO_PENDING";
export const ADD_ACHIEVEMENTS_INFO_REJECTED = "ADD_ACHIEVEMENTS_INFO_REJECTED";
export const UPDATE_ACHIEVEMENTS_INFO_FULFILLED =
  "UPDATE_ACHIEVEMENTS_INFO_FULFILLED";
export const UPDATE_ACHIEVEMENTS_INFO_REJECTED =
  "UPDATE_ACHIEVEMENTS_INFO_REJECTED";
export const UPDATE_ACHIEVEMENTS_INFO_PENDING =
  "UPDATE_ACHIEVEMENTS_INFO_PENDING";
export const GET_ACHIEVEMENTS_INFO_FULFILLED =
  "GET_ACHIEVEMENTS_INFO_FULFILLED";
export const GET_ACHIEVEMENTS_INFO_REJECTED = "GET_ACHIEVEMENTS_INFO_REJECTED";
export const GET_ACHIEVEMENTS_INFO_PENDING = "GET_ACHIEVEMENTS_INFO_PENDING";
