export const ADD_ACADEMIC_INFO_FULFILLED =
  "ADD_ACADEMIC_INFO_FULFILLED";
export const ADD_ACADEMIC_INFO_PENDING = "ADD_ACADEMIC_INFO_PENDING";
export const ADD_ACADEMIC_INFO_REJECTED = "ADD_ACADEMIC_INFO_REJECTED";
export const UPDATE_ACADEMIC_INFO_FULFILLED =
  "UPDATE_ACADEMIC_INFO_FULFILLED";
export const UPDATE_ACADEMIC_INFO_REJECTED =
  "UPDATE_ACADEMIC_INFO_REJECTED";
export const UPDATE_ACADEMIC_INFO_PENDING =
  "UPDATE_ACADEMIC_INFO_PENDING";
export const GET_ACADEMIC_INFO_FULFILLED =
  "GET_ACADEMIC_INFO_FULFILLED";
export const GET_ACADEMIC_INFO_REJECTED = "GET_ACADEMIC_INFO_REJECTED";
export const GET_ACADEMIC_INFO_PENDING = "GET_ACADEMIC_INFO_PENDING";
