export const ADD_AFFILIATIONS_INFO_FULFILLED =
  "ADD_AFFILIATIONS_INFO_FULFILLED";
export const ADD_AFFILIATIONS_INFO_PENDING = "ADD_AFFILIATIONS_INFO_PENDING";
export const ADD_AFFILIATIONS_INFO_REJECTED = "ADD_AFFILIATIONS_INFO_REJECTED";
export const UPDATE_AFFILIATIONS_INFO_FULFILLED =
  "UPDATE_AFFILIATIONS_INFO_FULFILLED";
export const UPDATE_AFFILIATIONS_INFO_REJECTED =
  "UPDATE_AFFILIATIONS_INFO_REJECTED";
export const UPDATE_AFFILIATIONS_INFO_PENDING =
  "UPDATE_AFFILIATIONS_INFO_PENDING";
export const GET_AFFILIATIONS_INFO_FULFILLED =
  "GET_AFFILIATIONS_INFO_FULFILLED";
export const GET_AFFILIATIONS_INFO_REJECTED = "GET_AFFILIATIONS_INFO_REJECTED";
export const GET_AFFILIATIONS_INFO_PENDING = "GET_AFFILIATIONS_INFO_PENDING";