export const ADD_ATTACHMENT_INFO_FULFILLED =
  "ADD_ATTACHMENT_INFO_FULFILLED";
export const ADD_ATTACHMENT_INFO_PENDING = "ADD_ATTACHMENT_INFO_PENDING";
export const ADD_ATTACHMENT_INFO_REJECTED = "ADD_ATTACHMENT_INFO_REJECTED";
export const UPDATE_ATTACHMENT_INFO_FULFILLED =
  "UPDATE_ATTACHMENT_INFO_FULFILLED";
export const UPDATE_ATTACHMENT_INFO_REJECTED =
  "UPDATE_ATTACHMENT_INFO_REJECTED";
export const UPDATE_ATTACHMENT_INFO_PENDING =
  "UPDATE_ATTACHMENT_INFO_PENDING";
export const GET_ATTACHMENT_INFO_FULFILLED =
  "GET_ATTACHMENT_INFO_FULFILLED";
export const GET_ATTACHMENT_INFO_REJECTED = "GET_ATTACHMENT_INFO_REJECTED";
export const GET_ATTACHMENT_INFO_PENDING = "GET_ATTACHMENT_INFO_PENDING";