export const ADD_CAPACITY_INFO_FULFILLED =
  "ADD_CAPACITY_INFO_FULFILLED";
export const ADD_CAPACITY_INFO_PENDING = "ADD_CAPACITY_INFO_PENDING";
export const ADD_CAPACITY_INFO_REJECTED = "ADD_CAPACITY_INFO_REJECTED";
export const UPDATE_CAPACITY_INFO_FULFILLED =
  "UPDATE_CAPACITY_INFO_FULFILLED";
export const UPDATE_CAPACITY_INFO_REJECTED =
  "UPDATE_CAPACITY_INFO_REJECTED";
export const UPDATE_CAPACITY_INFO_PENDING =
  "UPDATE_CAPACITY_INFO_PENDING";
export const GET_CAPACITY_INFO_FULFILLED =
  "GET_CAPACITY_INFO_FULFILLED";
export const GET_CAPACITY_INFO_REJECTED = "GET_CAPACITY_INFO_REJECTED";
export const GET_CAPACITY_INFO_PENDING = "GET_CAPACITY_INFO_PENDING";
