export const ADD_CERTIFICATIONS_INFO_FULFILLED =
  "ADD_CERTIFICATIONS_INFO_FULFILLED";
export const ADD_CERTIFICATIONS_INFO_PENDING = "ADD_CERTIFICATIONS_INFO_PENDING";
export const ADD_CERTIFICATIONS_INFO_REJECTED = "ADD_CERTIFICATIONS_INFO_REJECTED";
export const UPDATE_CERTIFICATIONS_INFO_FULFILLED =
  "UPDATE_CERTIFICATIONS_INFO_FULFILLED";
export const UPDATE_CERTIFICATIONS_INFO_REJECTED =
  "UPDATE_CERTIFICATIONS_INFO_REJECTED";
export const UPDATE_CERTIFICATIONS_INFO_PENDING =
  "UPDATE_CERTIFICATIONS_INFO_PENDING";
export const GET_CERTIFICATIONS_INFO_FULFILLED =
  "GET_CERTIFICATIONS_INFO_FULFILLED";
export const GET_CERTIFICATIONS_INFO_REJECTED = "GET_CERTIFICATIONS_INFO_REJECTED";
export const GET_CERTIFICATIONS_INFO_PENDING = "GET_CERTIFICATIONS_INFO_PENDING";
