export const ADD_EDUCATION_INFO_FULFILLED =
  "ADD_EDUCATION_INFO_FULFILLED";
export const ADD_EDUCATION_INFO_PENDING = "ADD_EDUCATION_INFO_PENDING";
export const ADD_EDUCATION_INFO_REJECTED = "ADD_EDUCATION_INFO_REJECTED";
export const UPDATE_EDUCATION_INFO_FULFILLED =
  "UPDATE_EDUCATION_INFO_FULFILLED";
export const UPDATE_EDUCATION_INFO_REJECTED =
  "UPDATE_EDUCATION_INFO_REJECTED";
export const UPDATE_EDUCATION_INFO_PENDING =
  "UPDATE_EDUCATION_INFO_PENDING";
export const GET_EDUCATION_INFO_FULFILLED =
  "GET_EDUCATION_INFO_FULFILLED";
export const GET_EDUCATION_INFO_REJECTED = "GET_EDUCATION_INFO_REJECTED";
export const GET_EDUCATION_INFO_PENDING = "GET_EDUCATION_INFO_PENDING";