export const ADD_PROJECTS_INFO_FULFILLED =
  "ADD_PROJECTS_INFO_FULFILLED";
export const ADD_PROJECTS_INFO_PENDING = "ADD_PROJECTS_INFO_PENDING";
export const ADD_PROJECTS_INFO_REJECTED = "ADD_PROJECTS_INFO_REJECTED";
export const UPDATE_PROJECTS_INFO_FULFILLED =
  "UPDATE_PROJECTS_INFO_FULFILLED";
export const UPDATE_PROJECTS_INFO_REJECTED =
  "UPDATE_PROJECTS_INFO_REJECTED";
export const UPDATE_PROJECTS_INFO_PENDING =
  "UPDATE_PROJECTS_INFO_PENDING";
export const GET_PROJECTS_INFO_FULFILLED =
  "GET_PROJECTS_INFO_FULFILLED";
export const GET_PROJECTS_INFO_REJECTED = "GET_PROJECTS_INFO_REJECTED";
export const GET_PROJECTS_INFO_PENDING = "GET_PROJECTS_INFO_PENDING";