export const ADD_REFERENCE_INFO_FULFILLED =
  "ADD_REFERENCE_INFO_FULFILLED";
export const ADD_REFERENCE_INFO_PENDING = "ADD_REFERENCE_INFO_PENDING";
export const ADD_REFERENCE_INFO_REJECTED = "ADD_REFERENCE_INFO_REJECTED";
export const UPDATE_REFERENCE_INFO_FULFILLED =
  "UPDATE_REFERENCE_INFO_FULFILLED";
export const UPDATE_REFERENCE_INFO_REJECTED =
  "UPDATE_REFERENCE_INFO_REJECTED";
export const UPDATE_REFERENCE_INFO_PENDING =
  "UPDATE_REFERENCE_INFO_PENDING";
export const GET_REFERENCE_INFO_FULFILLED =
  "GET_REFERENCE_INFO_FULFILLED";
export const GET_REFERENCE_INFO_REJECTED = "GET_REFERENCE_INFO_REJECTED";
export const GET_REFERENCE_INFO_PENDING = "GET_REFERENCE_INFO_PENDING";