export const ADD_REMARKS_INFO_FULFILLED =
  "ADD_REMARKS_INFO_FULFILLED";
export const ADD_REMARKS_INFO_PENDING = "ADD_REMARKS_INFO_PENDING";
export const ADD_REMARKS_INFO_REJECTED = "ADD_REMARKS_INFO_REJECTED";
export const UPDATE_REMARKS_INFO_FULFILLED =
  "UPDATE_REMARKS_INFO_FULFILLED";
export const UPDATE_REMARKS_INFO_REJECTED =
  "UPDATE_REMARKS_INFO_REJECTED";
export const UPDATE_REMARKS_INFO_PENDING =
  "UPDATE_REMARKS_INFO_PENDING";
export const GET_REMARKS_INFO_FULFILLED =
  "GET_REMARKS_INFO_FULFILLED";
export const GET_REMARKS_INFO_REJECTED = "GET_REMARKS_INFO_REJECTED";
export const GET_REMARKS_INFO_PENDING = "GET_REMARKS_INFO_PENDING";