export const USER_REGISTRATION_PENDING = "USER_REGISTRATION_PENDING";
export const USER_REGISTRATION_REJECTED = "USER_REGISTRATION_DETAILS_REJECTED";
export const USER_REGISTRATION_FULFILLED = "USER_REGISTRATION_FULLFILED";

export const USER_PROFILE_UPDATE_PENDING = "USER_PROFILE_UPDATE_PENDING";
export const USER_PROFILE_UPDATE_REJECTED =
  "USER_PROFILE_UPDATE_DETAILS_REJECTED";
export const USER_PROFILE_UPDATE_FULFILLED = "USER_PROFILE_UPDATE_FULLFILED";

export const USER_PROFILE_DELETE_PENDING = "USER_PROFILE_DELETE_PENDING";
export const USER_PROFILE_DELETE_REJECTED =
  "USER_PROFILE_DELETE_DETAILS_REJECTED";
export const USER_PROFILE_DELETE_FULFILLED = "USER_PROFILE_DELETE_FULLFILED";
