export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_REJECTED = "USER_LOGIN_DETAILS_REJECTED";
export const USER_LOGIN_FULFILLED = "USER_LOGIN_FULLFILED";
export const USER_LOGOUT = "USER_LOGOUT";
