export const ADD_ADDRESS_INFO_FULFILLED = "ADD_ADDRESS_INFO_FULFILLED";
export const ADD_ADDRESS_INFO_PENDING = "ADD_ADDRESS_INFO_PENDING";
export const ADD_ADDRESS_INFO_REJECTED = "ADD_ADDRESS_INFO_REJECTED";
