export const ADD_PERSONAL_INFO='ADD_PERSONAL_INFO'

export const ADD_ADDRESS_INFO='ADD_ADDRESS_INFO'
export const ADD_ACADEMIC_WORK_DETAILS='ADD_ACADEMIC_WORK_DETAILS'
export const ADD_WORK_EXPERIENCE='ADD_WORK_EXPERIENCE'

export const ADD_REFERENCE='ADD_REFERENCE'
export const ADD_EDUCATION='ADD_EDUCATION'
export const ADD_CAPACITY_DETAILS='ADD_CAPACITY_DETAILS'
export const ADD_CERTIFICATIONS_DETAILS='ADD_CERTIFICATIONS_DETAILS'