export const ADD_PERSONAL_INFO_FULFILLED = "ADD_PERSONAL_INFO_FULFILLED";
export const ADD_PERSONAL_INFO_REJECTED = "ADD_PERSONAL_INFO_REJECTED";
export const ADD_PERSONAL_INFO_PENDING = "ADD_PERSONAL_INFO_PENDING";
