export const GET_USER_LOGIN_DETAILS_PENDING = "GET_USER_LOGIN_DETAILS_PENDING";
export const GET_USER_LOGIN_DETAILS_REJECTED =
  "GET_USER_LOGIN_DETAILS_REJECTED";
export const GET_USER_LOGIN_DETAILS_FULFILLED =
  "GET_USER_LOGIN_DETAILS_FULLFILED";
export const USER_LOGOUT = "USER_LOGOUT";
