export const USER_REGISTRATION_PENDING = "USER_REGISTRATION_PENDING";
export const USER_REGISTRATION_REJECTED = "USER_REGISTRATION_DETAILS_REJECTED";
export const USER_REGISTRATION_FULFILLED = "USER_REGISTRATION_FULLFILED";
